# Assignment 3

Q1: K-Fold Cross Validation for Multiple Linear Regression (Least Square Error Fit)
Download the dataset regarding USA House Price Prediction from the following link:
https://drive.google.com/file/d/1O_NwpJT-8xGfU_-3llUl2sgPu0xllOrX/view?usp=sharing
Load the dataset and Implement 5- fold cross validation for multiple linear regression
(using least square error fit).
Steps:

a) Divide the dataset into input features (all columns except price) and output variable
(price)

b) Scale the values of input features.

c) Divide input and output features into five folds.

d) Run five iterations, in each iteration consider one-fold as test set and remaining four sets as training set. Find the beta (𝛽) matrix, predicted values, and R2_score for each iteration using least square error fit.

e) Use the best value of (𝛽) matrix (for which R2_score is maximum), to train the regressor for 70% of data and test the performance for remaining 30% data.

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,KFold
from sklearn.metrics import r2_score

In [8]:
data = pd.read_csv('/content/USA_Housing (1).csv')

In [9]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09      23086.80050  1.059034e+06  
1                          3.09      40173.07217  1.505891e+06  
2                          5.13      36882.15940  1.058988e+06  
3                          3.26      34310.24283  1.260617e+06  
4                          4.23      26354.10947  6.309435e+05

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB


In [14]:
X=data.drop(columns=['Price']).values
y=data['Price'].values.reshape(-1, 1)

In [15]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09      23086.80050  1.059034e+06  
1                          3.09      40173.07217  1.505891e+06  
2                          5.13      36882.15940  1.058988e+06  
3                          3.26      34310.24283  1.260617e+06  
4                          4.23      26354.10947  6.309435e+05

In [16]:
y=data['Price'].values.reshape(-1, 1)
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
kf=KFold(n_splits=5,shuffle=True,random_state=42)
best_beta=None
best_r2=-np.inf
print("5-Fold Cross Validation Results\n")
fold = 1

5-Fold Cross Validation Results



In [19]:

for train_index,test_index in kf.split(X_scaled):
    X_train,X_test=X_scaled[train_index],X_scaled[test_index]
    y_train,y_test=y[train_index],y[test_index]
    X_train_b=np.c_[np.ones((X_train.shape[0],1)),X_train]
    X_test_b=np.c_[np.ones((X_test.shape[0],1)),X_test]
    beta=np.linalg.inv(X_train_b.T@X_train_b)@(X_train_b.T@ y_train)
    y_pred = X_test_b @ beta
    r2 = r2_score(y_test, y_pred)
    print(f"Fold {fold}:")
    print(f" Beta Shape: {beta.shape}")
    print(f"R2 Score : {r2:.4f}\n")
    if r2>best_r2:
        best_r2=r2
        best_beta=beta
    fold+=1
print("Best R2 Score from CV:",best_r2)
print("Best Beta Matrix:\n",best_beta)


X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=42)


X_train_b=np.c_[np.ones((X_train.shape[0],1)),X_train]
X_test_b=np.c_[np.ones((X_test.shape[0],1)),X_test]


beta_final=np.linalg.inv(X_train_b.T@X_train_b)@(X_train_b.T@y_train)


y_pred_final=X_test_b@beta_final


final_r2=r2_score(y_test,y_pred_final)

print("\nFinal model that we have - (70/30 Split)")
print("Final Beta Matrix obtained:\n",beta_final)
print("Final R2 Score on Testing Data:",final_r2)


Fold 11:
 Beta Shape: (6, 1)
R2 Score : 0.9180

Fold 12:
 Beta Shape: (6, 1)
R2 Score : 0.9146

Fold 13:
 Beta Shape: (6, 1)
R2 Score : 0.9116

Fold 14:
 Beta Shape: (6, 1)
R2 Score : 0.9193

Fold 15:
 Beta Shape: (6, 1)
R2 Score : 0.9244

Best R2 Score from CV: 0.9243869413350317
Best Beta Matrix:
 [[1.23161736e+06]
 [2.30225051e+05]
 [1.63956839e+05]
 [1.21115120e+05]
 [7.83467170e+02]
 [1.50662447e+05]]

Final model that we have - (70/30 Split)
Final Beta Matrix obtained:
 [[1231278.63687691]
 [ 230464.52520478]
 [ 164159.19982569]
 [ 120514.71328324]
 [   2913.62424674]
 [ 151019.35865134]]
Final R2 Score on Testing Data: 0.9146818498916266


### Q2

Concept of Validation set for Multiple Linear Regression (Gradient Descent
Optimization)
Consider the same dataset of Q1, rather than dividing the dataset into five folds, divide the
dataset into training set (56%), validation set (14%), and test set (30%).
Consider four different values of learning rate i.e. {0.001,0.01,0.1,1}. Compute the values of
regression coefficients for each value of learning rate after 1000 iterations.
For each set of regression coefficients, compute R2_score for validation and test set and find
the best value of regression coefficients.

In [22]:
data = pd.read_csv("/content/USA_Housing (1).csv")

X = data.drop(columns=['Price']).values
y = data['Price'].values.reshape(-1, 1)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_scaled = np.c_[np.ones((X_scaled.shape[0], 1)), X_scaled]


X_train_val, X_test, y_train_val, y_test = train_test_split(
    X_scaled, y, test_size=0.30, random_state=42
)

# Now split 70% into 56% (train) and 14% (val)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.20, random_state=42
)  # 0.20 of 70% = 14%

print("Shapes:")
print(" Train:", X_train.shape, y_train.shape)
print(" Validation:", X_val.shape, y_val.shape)
print(" Test:", X_test.shape, y_test.shape)


def gradient_descent(X, y, lr, iters):
    m, n = X.shape
    beta = np.zeros((n, 1))

    for _ in range(iters):
        y_pred = X @ beta
        error = y_pred - y
        grad = (1/m) * (X.T @ error)
        beta -= lr * grad
    return beta


learning_rates = [0.001, 0.01, 0.1, 1]
iters = 1000

results = []

for lr in learning_rates:
    beta = gradient_descent(X_train, y_train, lr, iters)


    y_val_pred = X_val @ beta
    r2_val = r2_score(y_val, y_val_pred)

    y_test_pred = X_test @ beta
    r2_test = r2_score(y_test, y_test_pred)

    results.append((lr, beta, r2_val, r2_test))

    print(f"Learning Rate: {lr}")
    print(f"  Validation R2: {r2_val:.4f}")
    print(f"  Test R2      : {r2_test:.4f}\n")

best_result = max(results, key=lambda x: x[2])

best_lr, best_beta, best_r2_val, best_r2_test = best_result

print("------ Best Model ------")
print("Best Learning Rate of our best model:", best_lr)
print("Best Coefficients (Beta) achieved:\n", best_beta)
print("Best Validation R2:", best_r2_val)
print("Corresponding Test R2:", best_r2_test)


Shapes:
 Train: (2800, 6) (2800, 1)
 Validation: (700, 6) (700, 1)
 Test: (1500, 6) (1500, 1)
Learning Rate: 0.001
  Validation R2: -0.8125
  Test R2      : -0.9914

Learning Rate: 0.01
  Validation R2: 0.9098
  Test R2      : 0.9147

Learning Rate: 0.1
  Validation R2: 0.9098
  Test R2      : 0.9148

Learning Rate: 1
  Validation R2: 0.9098
  Test R2      : 0.9148

------ Best Model ------
Best Learning Rate of our best model: 0.01
Best Coefficients (Beta) achieved:
 [[1232562.51254919]
 [ 230048.76664688]
 [ 163686.93503606]
 [ 121406.94107918]
 [   3117.47363933]
 [ 150655.97459714]]
Best Validation R2: 0.9098183094422969
Corresponding Test R2: 0.9147434800538763


### Q3

Pre-processing and Multiple Linear Regression
Download the dataset regarding Car Price Prediction from the following link:
https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data
1. Load the dataset with following column names ["symboling", "normalized_losses",
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels",
"engine_location", "wheel_base", "length", "width", "height", "curb_weight",
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke",
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]
and replace all ? values with NaN
2. Replace all NaN values with central tendency imputation. Drop the rows with NaN
values in price column
3. There are 10 columns in the dataset with non-numeric values. Convert these values to
numeric values using following scheme:
(i) For “num_doors” and “num_cylinders”: convert words (number names) to figures
for e.g., two to 2
(ii) For "body_style", "drive_wheels": use dummy encoding scheme
(iii) For “make”, “aspiration”, “engine_location”,fuel_type: use label encoding
scheme
(iv) For fuel_system: replace values containing string pfi to 1 else all values to 0.
(v) For engine_type: replace values containing string ohc to 1 else all values to 0.
4. Divide the dataset into input features (all columns except price) and output variable
(price). Scale all input features.
5. Train a linear regressor on 70% of data (using inbuilt linear regression function of
Python) and test its performance on remaining 30% of data.
6. Reduce the dimensionality of the feature set using inbuilt PCA decomposition and then
again train a linear regressor on 70% of reduced data (using inbuilt linear regression
function of Python). Does it lead to any performance improvement on test set?

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
from sklearn.metrics import r2_score

columns = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration", "num_doors",
           "body_style", "drive_wheels", "engine_location", "wheel_base", "length", "width",
           "height", "curb_weight", "engine_type", "num_cylinders", "engine_size",
           "fuel_system", "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
data = pd.read_csv(url, names=columns)


data = data.replace("?", np.nan)



In [25]:

for col in data.columns:
    if data[col].dtype == 'object':

        data[col].fillna(data[col].mode()[0], inplace=True)
    else:

        data[col] = pd.to_numeric(data[col], errors="coerce")  # convert to numeric first
        data[col].fillna(data[col].mean(), inplace=True)



/tmp/ipython-input-743684026.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)
/tmp/ipython-input-743684026.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try usin

In [26]:

data = data.dropna(subset=['price'])
data['price'] = data['price'].astype(float)


door_map = {"two": 2, "four": 4}
cyl_map = {"two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "eight": 8, "twelve": 12}
data['num_doors'] = data['num_doors'].map(door_map)
data['num_cylinders'] = data['num_cylinders'].map(cyl_map)


data = pd.get_dummies(data, columns=["body_style", "drive_wheels"], drop_first=True)


In [27]:

for col in ["make", "aspiration", "engine_location", "fuel_type"]:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])


data['fuel_system'] = data['fuel_system'].apply(lambda x: 1 if 'pfi' in x else 0)

data['engine_type'] = data['engine_type'].apply(lambda x: 1 if 'ohc' in x else 0)


X = data.drop(columns=['price']).values
y = data['price'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

reg = LinearRegression()
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)
r2_original = r2_score(y_test, y_pred)

In [29]:


print("Performance with original features:")
print(" R2 Score:", r2_original)


pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.3, random_state=42)

reg_pca = LinearRegression()
reg_pca.fit(X_train_pca, y_train_pca)

y_pred_pca = reg_pca.predict(X_test_pca)
r2_pca = r2_score(y_test_pca, y_pred_pca)

print("\nPerformance with PCA-reduced features:")
print(" R2 Score:", r2_pca)


if r2_pca > r2_original:
    print("\n PCA successfully improved our performance!")
else:
    print("\n PCA failed to improve performance.")


Performance with original features:
 R2 Score: 0.7895045576733848

Performance with PCA-reduced features:
 R2 Score: 0.7478420860380317

 PCA failed to improve performance.
